@startuml 'gamitude database model'

class User {
    String id
    String email
    long money
    String currentRankId
    String currentThemeId
    List<String> timers
    List<String> purchasedRankIds
    List<String> purchasedThemeIds
    Date dateCreated
}
class UserToken{
    String id
    String userId
    String token
    String dateExpires
}

class Stats{
    String id
    String userId
    long strength
    long intelligence
    long fluency
    long creativity
}

class Folder{
    String id
    String userId
    String name
    String description
    String icon
    Date dateCreated
}

class Project{
    String id
    String userId
    String folderId
    String defaultTimerId
    String name
    Project_type projectType
    Stats dominantStat
    Stats[] stats
    Date dateCreated
    int dayPerWeek
    int hourPerDay
    int totalTimeSpend
    int timeSpendBreak
}

class Journal{
    String id
    String userId
    String projectId
    String name
    String icon
    String description
    Date dateCreated
}
class Page{
    String id
    String userId
    String journalId
    String name
    BetweenDays betweenDays
    String description
    String description
    Page_type pageType
    Date dateCreated
}
class BetweenDays{
    int fromDay
    int toDay
}
class ProjectTask{
    String id
    String userId
    String journalId
    String projectId
    String name
    String description
    String note
    List<String> tags
    Date deadLine
    Date dateCreated
    Date dateFinished
}

class ProjectLog{
    String id
    String userId
    Project project
    ProjectTask projectTask
    String log
    Project_type type
    Stats[] stats
    Date dateCreated
    int timeSpend
}

class Timer{
    String id
    String userId
    String name
    String label
    Timer_type timerType
    CountDownInfo countDownInfo
    Date dateCreated
}
class CountDownInfo{
    int workTime
    int breakTime
    int overTime
    int longerBreakTime
    int breakInterval
}

class Rank{
    String id
    String name
    String imgUrl
    bool rookie
    Gamitude_style style
    Rank_tier tier
    Rank_dominant dominant
    long priceStrength
    long priceIntelligence
    long priceFluency
    long priceCreativity
    long priceEuro
}

class Theme{
    String id
    String name
    ColorPallet colorPallet
    long priceStrength
    long priceIntelligence
    long priceFluency
    long priceCreativity
    long priceEuro
}


class DailyEnergy{
    String id
    String userId
    Date date
    int mind
    int soul
    int body
    int emotions
}


User "1" *-- "many" Timer
User "1" <--> "1" Stats
User "1" <--> "1" UserToken
User "1" *-- "many" Folder
User "many" *--* "many" Rank
User "many" *--* "many" Theme
Folder "1" *-- "many" Project
User "1" *-- "many" DailyEnergy
Project "1" *-- "many" ProjectLog
ProjectTask "1" *-- "many" ProjectLog
User "1" *-- "many" Journal
Journal "1" *-- "many" Page
Journal "1" *-- "many" ProjectTask


@enduml

